services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - all-in-one

  api:
    build:
      context: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_DATABASE=postgres
      - JWT_ACCESS_SECRET=access-secret-monolith
      - JWT_REFRESH_SECRET=refresh-secret-monolith
    networks:
      - all-in-one

volumes:
  pgdata:
    driver: local

networks:
  all-in-one:
    driver: bridge